// =============================================================================
// EditorIcons.h — Generated from selection.icomoon.json
// Font: OctaveIcons.ttf | 250 icons | Range: U+F000..U+F0F9
// =============================================================================
#pragma once

#include "imgui.h"

// ---------------------------------------------------------------------------
// Glyph range
// ---------------------------------------------------------------------------
static constexpr ImWchar kIconMin = 0xF000;
static constexpr ImWchar kIconMax = 0xF0F9;

static const ImWchar kIconRanges[] = { 0xF000, 0xF0F9, 0 };

// ---------------------------------------------------------------------------
// Icon definitions (sorted alphabetically by identifier)
// ---------------------------------------------------------------------------
#define ICON_9POINT                                                 u8"\uF0F5"
#define ICON_ANT_DESIGN_THUNDERBOLT_FILLED                          u8"\uF0F2"
#define ICON_ASSETS                                                 u8"\uF0EF"
#define ICON_BASIL_EYE_CLOSED_SOLID                                 u8"\uF0EC"
#define ICON_BEZIER                                                 u8"\uF0E9"
#define ICON_BITCOIN_ICONS_NODE_2_CONNECTIONS_FILLED                u8"\uF0E3"
#define ICON_BI_UNITY                                               u8"\uF0E6"
#define ICON_BLUETOOTH                                              u8"\uF0E0"
#define ICON_BOXICONS_ANIMATION_BOUNCE                              u8"\uF0DD"
#define ICON_BOXICONS_EYEDROPPER_FILLED                             u8"\uF0F8"
#define ICON_BOXICONS_PAINT                                         u8"\uF0DA"
#define ICON_BOXICONS_SHAPE_ROTATE_CW                               u8"\uF0D7"
#define ICON_BUTTON                                                 u8"\uF0D4"
#define ICON_BXS_ARROW_TO_BOTTOM                                    u8"\uF0C8"
#define ICON_BXS_GRID                                               u8"\uF0C5"
#define ICON_BXS_PURCHASE_TAG_ALT                                   u8"\uF0C2"
#define ICON_BXS_TREE                                               u8"\uF0BF"
#define ICON_BX_MATH                                                u8"\uF0D1"
#define ICON_BX_MOVE                                                u8"\uF0CE"
#define ICON_BX_PACKAGE                                             u8"\uF0CB"
#define ICON_CANVAS                                                 u8"\uF0BC"
#define ICON_CAPSULE                                                u8"\uF0B9"
#define ICON_CARBON_EDGE_NODE                                       u8"\uF0B6"
#define ICON_CBI_DREAMCAST                                          u8"\uF0B3"
#define ICON_CIB_EPIC_GAMES                                         u8"\uF0B0"
#define ICON_CIB_NINTENDO_3DS                                       u8"\uF0AD"
#define ICON_CIB_NINTENDO_GAMECUBE                                  u8"\uF0AA"
#define ICON_CIB_PLAYSTATION3                                       u8"\uF0A7"
#define ICON_CIB_PLAYSTATION4                                       u8"\uF0A4"
#define ICON_CIB_WII                                                u8"\uF0A1"
#define ICON_CLAPPERBOARD_CLOSE                                     u8"\uF09E"
#define ICON_CLAPPERBOARD_OPEN                                      u8"\uF09B"
#define ICON_CLARITY_MOBILE_SOLID                                   u8"\uF098"
#define ICON_CLARITY_NO_ACCESS_SOLID                                u8"\uF095"
#define ICON_CONSOLE                                                u8"\uF092"
#define ICON_CPP                                                    u8"\uF08F"
#define ICON_CS                                                     u8"\uF08C"
#define ICON_CURVEGRAPH                                             u8"\uF089"
#define ICON_DASHICONS_ARROW_DOWN                                   u8"\uF083"
#define ICON_DASHICONS_ARROW_UP                                     u8"\uF0DC"
#define ICON_DASHICONS_NO_ALT                                       u8"\uF080"
#define ICON_EP_SET_UP                                              u8"\uF07D"
#define ICON_EVA_NAVIGATION_2_FILL                                  u8"\uF07A"
#define ICON_FA6_SOLID_COMPUTER                                     u8"\uF077"
#define ICON_FA7_SOLID_MOUNTAIN_CITY                                u8"\uF074"
#define ICON_FA_SOLID_MONEY_BILL_WAVE                               u8"\uF071"
#define ICON_FE_GAMEPAD                                             u8"\uF06E"
#define ICON_FILE_ICONS_GODOT                                       u8"\uF06B"
#define ICON_FILTER                                                 u8"\uF069"
#define ICON_FIREWORK                                               u8"\uF067"
#define ICON_FLUENT_BOT_28_FILLED                                   u8"\uF065"
#define ICON_FLUENT_BOX_SEARCH_24_FILLED                            u8"\uF063"
#define ICON_FLUENT_KEY_16_FILLED                                   u8"\uF061"
#define ICON_FLUENT_MDL2_CUBE_SHAPE                                 u8"\uF04D"
#define ICON_FLUENT_MDL2_FIVE_TILE_GRID                             u8"\uF04B"
#define ICON_FLUENT_MDL2_PICTURE_TILE                               u8"\uF049"
#define ICON_FLUENT_MOUNTAIN_LOCATION_BOTTOM_28_FILLED              u8"\uF05F"
#define ICON_FLUENT_MOUNTAIN_LOCATION_TOP_24_FILLED                 u8"\uF05D"
#define ICON_FLUENT_MOUNTAIN_TRAIL_20_FILLED                        u8"\uF05B"
#define ICON_FLUENT_SCALE_FIT_16_REGULAR                            u8"\uF059"
#define ICON_FLUENT_SLIDE_SEARCH_24_FILLED                          u8"\uF057"
#define ICON_FLUENT_SPACE_3D_32_REGULAR                             u8"\uF055"
#define ICON_FLUENT_SPARKLE_16_FILLED                               u8"\uF053"
#define ICON_FLUENT_TAG_24_FILLED                                   u8"\uF051"
#define ICON_FLUENT_TAG_ADD_24_FILLED                               u8"\uF04F"
#define ICON_GLOBE                                                  u8"\uF047"
#define ICON_GRIDICONS_CUSTOM_POST_TYPE                             u8"\uF045"
#define ICON_GROMMET_ICONS_CUBES                                    u8"\uF043"
#define ICON_HEROICONS_PAINT_BRUSH_20_SOLID                         u8"\uF041"
#define ICON_HIERARCHY                                              u8"\uF03F"
#define ICON_HUGEICONS_MATERIAL_AND_TEXTURE                         u8"\uF03D"
#define ICON_ICONOIR_SUN_LIGHT                                      u8"\uF01B"
#define ICON_ICON_PARK_OUTLINE_DOME_LIGHT                           u8"\uF019"
#define ICON_ICON_PARK_OUTLINE_SCALE_ONE                            u8"\uF017"
#define ICON_ICON_PARK_SOLID_INNER_SHADOW_BOTTOM_LEFT               u8"\uF015"
#define ICON_ICON_PARK_SOLID_MOUNTAIN                               u8"\uF013"
#define ICON_IC_BASELINE_APPLE                                      u8"\uF03B"
#define ICON_IC_BASELINE_DOWNLOAD                                   u8"\uF039"
#define ICON_IC_BASELINE_HOURGLASS_BOTTOM                           u8"\uF037"
#define ICON_IC_BASELINE_LINEAR_SCALE                               u8"\uF035"
#define ICON_IC_BASELINE_LINK                                       u8"\uF033"
#define ICON_IC_BASELINE_LIST                                       u8"\uF031"
#define ICON_IC_BASELINE_PEOPLE                                     u8"\uF02F"
#define ICON_IC_BASELINE_SEARCH                                     u8"\uF02D"
#define ICON_IC_BASELINE_SHARE                                      u8"\uF02B"
#define ICON_IC_BASELINE_STOP                                       u8"\uF029"
#define ICON_IC_BASELINE_UPLOAD                                     u8"\uF027"
#define ICON_IC_OUTLINE_LOOP                                        u8"\uF025"
#define ICON_IC_ROUND_COMPUTER                                      u8"\uF023"
#define ICON_IC_SHARP_EXTENSION                                     u8"\uF021"
#define ICON_IC_SHARP_SETTINGS_BACKUP_RESTORE                       u8"\uF01F"
#define ICON_IC_TWOTONE_POWER_SETTINGS_NEW                          u8"\uF01D"
#define ICON_INFO                                                   u8"\uF011"
#define ICON_ION_HAMMER_SHARP                                       u8"\uF00F"
#define ICON_IX_CODE                                                u8"\uF00D"
#define ICON_IX_VIDEO_CAMERA_FILLED                                 u8"\uF00B"
#define ICON_IX_VIDEO_FILE_FILLED                                   u8"\uF009"
#define ICON_JSON                                                   u8"\uF007"
#define ICON_LAYERS                                                 u8"\uF005"
#define ICON_LIGHTBULB                                              u8"\uF003"
#define ICON_LINEICONS_VECTOR_NODES_7                               u8"\uF001"
#define ICON_LINE_MD_PAINT_DROP_FILLED                              u8"\uF0F4"
#define ICON_LUA                                                    u8"\uF0F1"
#define ICON_LUCIDE_ROTATE_3D                                       u8"\uF0EE"
#define ICON_LUCIDE_SPOTLIGHT                                       u8"\uF0EB"
#define ICON_MAGE_SCALE_UP                                          u8"\uF0E8"
#define ICON_MAJESTICONS_MAP_MARKER                                 u8"\uF0E5"
#define ICON_MATERIAL_SYMBOLS_ADD                                   u8"\uF0E2"
#define ICON_MATERIAL_SYMBOLS_ADD_AD_SHARP                          u8"\uF0DF"
#define ICON_MATERIAL_SYMBOLS_ARROW_LEFT                            u8"\uF0D9"
#define ICON_MATERIAL_SYMBOLS_ARROW_RIGHT                           u8"\uF086"
#define ICON_MATERIAL_SYMBOLS_AUDIO_FILE_SHARP                      u8"\uF0D6"
#define ICON_MATERIAL_SYMBOLS_BOMB                                  u8"\uF0D3"
#define ICON_MATERIAL_SYMBOLS_CHECK                                 u8"\uF0D0"
#define ICON_MATERIAL_SYMBOLS_CHECK_CIRCLE                          u8"\uF0CD"
#define ICON_MATERIAL_SYMBOLS_CLOUD_OUTLINE                         u8"\uF0CA"
#define ICON_MATERIAL_SYMBOLS_DEVICE_RESET                          u8"\uF0C7"
#define ICON_MATERIAL_SYMBOLS_DOCUMENT_SEARCH_SHARP                 u8"\uF0C4"
#define ICON_MATERIAL_SYMBOLS_FILE_COPY_SHARP                       u8"\uF0C1"
#define ICON_MATERIAL_SYMBOLS_FLAG                                  u8"\uF0BE"
#define ICON_MATERIAL_SYMBOLS_FOLDER_OPEN_SHARP                     u8"\uF0BB"
#define ICON_MATERIAL_SYMBOLS_FOLDER_SHARP                          u8"\uF0B8"
#define ICON_MATERIAL_SYMBOLS_IMAGE_SEARCH_SHARP                    u8"\uF0B5"
#define ICON_MATERIAL_SYMBOLS_LIGHT_FAST_FORWARD                    u8"\uF076"
#define ICON_MATERIAL_SYMBOLS_LIGHT_FAST_FORWARD_1                  u8"\uF073"
#define ICON_MATERIAL_SYMBOLS_LIGHT_MOUNTAIN_STEAM_ROUNDED          u8"\uF070"
#define ICON_MATERIAL_SYMBOLS_LOCK_OPEN_SHARP                       u8"\uF0B2"
#define ICON_MATERIAL_SYMBOLS_LOCK_SHARP                            u8"\uF0AF"
#define ICON_MATERIAL_SYMBOLS_MANAGE_SEARCH                         u8"\uF0AC"
#define ICON_MATERIAL_SYMBOLS_MIC                                   u8"\uF0A9"
#define ICON_MATERIAL_SYMBOLS_MOUNTAIN_FLAG_OUTLINE                 u8"\uF0A6"
#define ICON_MATERIAL_SYMBOLS_NOTE_ADD_SHARP                        u8"\uF0A3"
#define ICON_MATERIAL_SYMBOLS_PAUSE                                 u8"\uF0A0"
#define ICON_MATERIAL_SYMBOLS_PERSON                                u8"\uF09D"
#define ICON_MATERIAL_SYMBOLS_PERSON_SEARCH                         u8"\uF09A"
#define ICON_MATERIAL_SYMBOLS_POWER_SETTINGS_CIRCLE                 u8"\uF097"
#define ICON_MATERIAL_SYMBOLS_RESET_ISO                             u8"\uF094"
#define ICON_MATERIAL_SYMBOLS_ROCKET_LAUNCH                         u8"\uF091"
#define ICON_MATERIAL_SYMBOLS_SAVE_SHARP                            u8"\uF08E"
#define ICON_MATERIAL_SYMBOLS_SETTINGS                              u8"\uF08B"
#define ICON_MATERIAL_SYMBOLS_STAR                                  u8"\uF088"
#define ICON_MATERIAL_SYMBOLS_TARGET                                u8"\uF085"
#define ICON_MATERIAL_SYMBOLS_TV_OUTLINE_ROUNDED                    u8"\uF082"
#define ICON_MATERIAL_SYMBOLS_VIEW_TIMELINE_SHARP                   u8"\uF07F"
#define ICON_MATERIAL_SYMBOLS_WARNING                               u8"\uF07C"
#define ICON_MATERIAL_SYMBOLS_WIDGET_MEDIUM                         u8"\uF079"
#define ICON_MDI_ANIMATION                                          u8"\uF06D"
#define ICON_MDI_ANIMATION_MINUS                                    u8"\uF06A"
#define ICON_MDI_ANIMATION_PLAY                                     u8"\uF068"
#define ICON_MDI_ANIMATION_PLUS                                     u8"\uF066"
#define ICON_MDI_AWS                                                u8"\uF064"
#define ICON_MDI_AXIS_ARROW                                         u8"\uF062"
#define ICON_MDI_BUG                                                u8"\uF060"
#define ICON_MDI_CART                                               u8"\uF05E"
#define ICON_MDI_CONTENT_PASTE                                      u8"\uF05C"
#define ICON_MDI_DOLPHIN                                            u8"\uF05A"
#define ICON_MDI_ERASER                                             u8"\uF0F6"
#define ICON_MDI_EYE                                                u8"\uF058"
#define ICON_MDI_FOLDER_SEARCH_OUTLINE                              u8"\uF056"
#define ICON_MDI_GIFT                                               u8"\uF054"
#define ICON_MDI_LINUX                                              u8"\uF052"
#define ICON_MDI_MAGIC                                              u8"\uF050"
#define ICON_MDI_MIXER_SETTINGS_VERTICAL                            u8"\uF04E"
#define ICON_MDI_MOVIE_SEARCH                                       u8"\uF04C"
#define ICON_MDI_NINTENDO_WIIU                                      u8"\uF04A"
#define ICON_MDI_PENCIL                                             u8"\uF048"
#define ICON_MDI_PEOPLE_ADD                                         u8"\uF046"
#define ICON_MDI_PLAY                                               u8"\uF044"
#define ICON_MDI_RESISTOR_NODES                                     u8"\uF042"
#define ICON_MDI_SERVER_OUTLINE                                     u8"\uF040"
#define ICON_MDI_STEAM                                              u8"\uF03E"
#define ICON_MDI_TABLE_SEARCH                                       u8"\uF03C"
#define ICON_MDI_TARGET                                             u8"\uF03A"
#define ICON_MDI_THUMBS_DOWN                                        u8"\uF038"
#define ICON_MDI_THUMBS_UP                                          u8"\uF036"
#define ICON_MDI_THUMBS_UP_1                                        u8"\uF034"
#define ICON_MDI_WEBCAM                                             u8"\uF032"
#define ICON_MINGCUTE_PAPER_FILL                                    u8"\uF030"
#define ICON_MINGCUTE_SCALE_LINE                                    u8"\uF02E"
#define ICON_MINGCUTE_SCISSORS_FILL                                 u8"\uF0F9"
#define ICON_NIMBUS_BROWSER_SEARCH                                  u8"\uF02C"
#define ICON_OCTICON_MIRROR_X                                       u8"\uF02A"
#define ICON_OCTICON_MIRROR_Y                                       u8"\uF028"
#define ICON_PH_CURSOR_TEXT_LIGHT                                   u8"\uF026"
#define ICON_PH_MAGNET_FILL                                         u8"\uF024"
#define ICON_PH_MUSIC_NOTE_FILL                                     u8"\uF022"
#define ICON_PH_PANORAMA_FILL                                       u8"\uF020"
#define ICON_PH_PAPER_PLANE_TILT_FILL                               u8"\uF01E"
#define ICON_PH_SPHERE                                              u8"\uF01C"
#define ICON_POLYGON                                                u8"\uF01A"
#define ICON_QLEMENTINE_ICONS_WAVE_16                               u8"\uF018"
#define ICON_RAPHAEL_NO                                             u8"\uF016"
#define ICON_RECT                                                   u8"\uF014"
#define ICON_RECTFILL                                               u8"\uF0F7"
#define ICON_RIVET_ICONS_AUDIO_SOLID                                u8"\uF002"
#define ICON_RI_CURSOR_FILL                                         u8"\uF012"
#define ICON_RI_FIGMA_LINE                                          u8"\uF010"
#define ICON_RI_NETWORK_FILL                                        u8"\uF00E"
#define ICON_RI_PAINT_FILL                                          u8"\uF00C"
#define ICON_RI_PLAYSTATION_FILL                                    u8"\uF00A"
#define ICON_RI_REWIND_START_FILL                                   u8"\uF008"
#define ICON_RI_SWITCH_FILL                                         u8"\uF006"
#define ICON_RI_WINDOWS_FILL                                        u8"\uF004"
#define ICON_SAVEAS                                                 u8"\uF000"
#define ICON_SCENE                                                  u8"\uF0F3"
#define ICON_SHADOW                                                 u8"\uF0F0"
#define ICON_SIMPLE_ICONS_PLAYSTATION2                              u8"\uF0ED"
#define ICON_SIMPLE_ICONS_PLAYSTATION5                              u8"\uF0EA"
#define ICON_SIMPLE_ICONS_PLAYSTATIONPORTABLE                       u8"\uF0E7"
#define ICON_SIMPLE_ICONS_PLAYSTATIONVITA                           u8"\uF0E4"
#define ICON_SIMPLE_ICONS_RETROARCH                                 u8"\uF0E1"
#define ICON_SKELETON                                               u8"\uF0DE"
#define ICON_SOLAR_PANORAMA_BOLD                                    u8"\uF0DB"
#define ICON_SPLINE                                                 u8"\uF0D8"
#define ICON_STREAMLINE_LOGOS_UNREAL_ENGINE_LOGO_SOLID              u8"\uF0CF"
#define ICON_STREAMLINE_LOG_SOLID                                   u8"\uF0D5"
#define ICON_STREAMLINE_PAINT_PALETTE_REMIX                         u8"\uF0D2"
#define ICON_STREAMLINE_PLUMP_WORLD_REMIX                           u8"\uF0CC"
#define ICON_STREAMLINE_SHARP_GAMEBOY_SOLID                         u8"\uF0C9"
#define ICON_STREAMLINE_SHARP_NEW_FILE_REMIX                        u8"\uF0C6"
#define ICON_STREAMLINE_SHARP_WAVE_SIGNAL_REMIX                     u8"\uF0C3"
#define ICON_STREAMLINE_ULTIMATE_NAVIGATION_MENU_HORIZONTAL_1_BOLD  u8"\uF0C0"
#define ICON_SUN                                                    u8"\uF0BD"
#define ICON_TABLER_CHAIR_DIRECTOR                                  u8"\uF0BA"
#define ICON_TABLER_HAND_GRAB                                       u8"\uF0B7"
#define ICON_TABLER_MESH                                            u8"\uF0B4"
#define ICON_TABLER_PAINT                                           u8"\uF0B1"
#define ICON_TABLER_WORLD_SEARCH                                    u8"\uF0AE"
#define ICON_TDESIGN_ANIMATION_1                                    u8"\uF0AB"
#define ICON_TDESIGN_ANIMATION_FILLED                               u8"\uF0A8"
#define ICON_TDESIGN_IMAGE_FILLED                                   u8"\uF0A5"
#define ICON_TDESIGN_IMAGE_SEARCH_FILLED                            u8"\uF0A2"
#define ICON_TDESIGN_NOTIFICATION_FILLED                            u8"\uF09F"
#define ICON_TDESIGN_TABLE_FILLED                                   u8"\uF09C"
#define ICON_TEENYICONS_N64_SOLID                                   u8"\uF099"
#define ICON_TERRAIN_FLATTEN                                        u8"\uF096"
#define ICON_TERRAIN_LOWER                                          u8"\uF093"
#define ICON_TERRAIN_RAISE                                          u8"\uF090"
#define ICON_TERRAIN_SMOOTH                                         u8"\uF08D"
#define ICON_TEXTMESH                                               u8"\uF08A"
#define ICON_TEXTWIDGET                                             u8"\uF087"
#define ICON_TORUS                                                  u8"\uF084"
#define ICON_TYPEICON                                               u8"\uF081"
#define ICON_UIL_ANDROID                                            u8"\uF07E"
#define ICON_UIWIDGET                                               u8"\uF07B"
#define ICON_UNDO                                                   u8"\uF078"
#define ICON_VIEWPORT3D                                             u8"\uF075"
#define ICON_WIFI                                                   u8"\uF072"
#define ICON_ZONDICONS_EXCLAMATION_SOLID                            u8"\uF06F"
#define ICON_ZONDICONS_TRASH                                        u8"\uF06C"

// ---------------------------------------------------------------------------
// Semantic aliases for common editor toolbar icons
// ---------------------------------------------------------------------------
#define ICON_STATIC_MESH            ICON_FLUENT_MDL2_CUBE_SHAPE                // Single cube
#define ICON_INSTANCE_MESH          ICON_GROMMET_ICONS_CUBES                   // Multiple cubes
#define ICON_TIMELINE               ICON_MATERIAL_SYMBOLS_VIEW_TIMELINE_SHARP  // Timeline


// ---------------------------------------------------------------------------
// Helper: merge PolyphaseEngineIcons.ttf into an existing ImGui font atlas
// ---------------------------------------------------------------------------
inline void MergePolyphaseIcons(ImFontAtlas* atlas, float pixelSize, const char* ttfPath)
{
    ImFontConfig cfg;
    cfg.MergeMode = true;
    cfg.PixelSnapH = true;
    cfg.GlyphMinAdvanceX = pixelSize;
    atlas->AddFontFromFileTTF(ttfPath, pixelSize, &cfg, kIconRanges);
}
